plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = 'es.upm.miw.persistenciasf'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId = 'es.upm.miw.persistenciasf'
        minSdk = 25
        targetSdk = 37
        versionCode = 1
        versionName = '1.0'
    }

    buildTypes {
        release {
            optimization {
                enable = false
            }
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation libs.core
	implementation libs.appcompat
	implementation libs.material
    implementation libs.constraintLayout
    implementation libs.preference
}